---
name: container-image
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}


permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  image:
    name: Build and Push Image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        ## ARN from tf/modules/build output
        role-to-assume: arn:aws:iam::832855882461:role/github-jmanero-ubiquitous-guacamole
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Image
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        ## Repository created by tf/modules/build
        image: functions/ubiquitous-guacamole
        tags: latest 0.0.1-git.${{ github.sha }}
        context: .
        containerfiles: Containerfile
        labels: |-
          org.label-schema.vcs-url=${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          org.label-schema.vcs-ref=${{ github.sha }}

    - name: Push Image to ECR
      id: push-ecr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        ## Registry for AWS account
        ## TODO: Apply build module in this workflow to get outputs
        registry: 832855882461.dkr.ecr.us-east-1.amazonaws.com

    - name: Push Image to GitHub Packages
      id: push-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ghcr.io/jmanero
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
